### ISSUE TITLE
Reconsider licensing

### ISSUE THREAD

**Issue by Downchuck** [baratine/auction#1]
As example code for using Baratine, the GPL license means that none of the code can actually be used in any copy-paste style, without the GPL applying to the derived project.

This more-or-less means that we can't use auction as a frame of reference if we're not generating GPL code... Apache 2.0 is more standard in the Java world, MIT or BSD are generally accepted. Boost and CC0 are not really used often in Java, but are a bit more appropriate for example source code such as this.

**Comment by carojkov** [comment]
License changed to Apache 2.0. 

Thanks for your interest.
